imports:
    - { resource: graphql.yml }
    - { resource: eventlistener.yml }

services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # auto-register all commands as services
    Pimcore\Bundle\DataHubBundle\Command\:
        resource: '../../Command'

    Pimcore\Bundle\DataHubBundle\Controller\:
        resource: '../../Controller'
        public: true
        autowire: true
        autoconfigure: true
        tags: ['controller.service_arguments']
    
    Pimcore\Bundle\DataHubBundle\Service\:
        resource: '../../Service'
        public: true
        autowire: true
        autoconfigure: true

    Pimcore\Bundle\DataHubBundle\Lock\:
        resource: '../../Lock'

    Pimcore\Bundle\DataHubBundle\MessageHandler\:
        resource: '../../MessageHandler'
        public: false

    Pimcore\Bundle\DataHubBundle\Messenger\PriorityRedisTransportFactory:
        arguments:
            $container: '@parameter_bag'
        tags:
            - { name: messenger.transport_factory }

    Pimcore\Bundle\DataHubBundle\Installer:
        public: true
        arguments:
            $bundle: "@=service('kernel').getBundle('PimcoreDataHubBundle')"

when@test:
    services:
        _defaults:
            autowire: true
            autoconfigure: true
            public: false

        Pimcore\Bundle\DataHubBundle\Tests\Functional\Commands\:
            resource: '../../../../tests/Functional/Commands'